version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: paWWWssWord
    networks:
    - udomiljubimca_dev
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: paWWWssWord
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa565w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
    - udomiljubimca_dev
  nginx-proxy:
    container_name: nginx
    build:
      context: ./nginx-proxy
    image: nginx:alpine
    ports:
    - 80:80
    networks:
    - udomiljubimca_dev
  register-api:
    container_name: register-api
    build:
      context: ./register-api
      # args: 
      #   TEST: Test
    image: udomiljubimca/register-api:1.0
    ports:
    - 8081:8080
    networks:
    - udomiljubimca_dev
networks:
  udomiljubimca_dev:
    driver: bridge