version: '3'

volumes:
  postgres_data:
      driver: local

services:
  register-api:
    container_name: register-api
    build:
      context: ./
      # args: 
      #   TEST: Test
    image: udomiljubimca/register-api:1.0
    environment: 
      FLASK_ENV: ${FLASK_ENV}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      CLIENT_RELM_SECRET: ${CLIENT_RELM_SECRET}
      CLIENT_RELM_NAME: ${CLIENT_RELM_NAME}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_CLIENT_NAME: ${KEYCLOAK_CLIENT_NAME}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
    ports:
    - 8081:8080
    networks:
    - udomiljubimca_dev
networks:
  udomiljubimca_dev:
    external:
      name: udomiljubimca_dev