version: '3'

volumes:
  postgres_data:
      driver: local

services:
  register-api:
    container_name: register-api
    build:
      context: ./
      # args: 
      #   TEST: Test
    image: udomiljubimca/register-api:1.0
    ports:
    - 8081:8080
    networks:
    - udomiljubimca_dev
networks:
  udomiljubimca_dev:
    driver: bridge